catalogs:
  eslint:
    "@virtual-live-lab/eslint-config": 2.2.22
    eslint: 9.30.1
    typescript-eslint: 8.36.0
  prettier:
    "@virtual-live-lab/prettier-config": 2.0.19
    prettier: 3.6.2
  tsconfig:
    "@types/node": 22.15.32
    "@virtual-live-lab/tsconfig": 2.1.20

managePackageManagerVersions: true
