name: PR Helper

on:
  pull_request:
    branches:
      - main
defaults:
  run:
    shell: bash

jobs:
  check:
    name: PR Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js and pnpm
        uses: ./.github/common/setup-node-pnpm

      - name: Run Tests
        run: |
          pnpm lint:check
          pnpm format:check
